<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-boat',
                'id' => 1,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.dashboard',
                'target' => '_self',
                'title' => 'Dashboard',
                'updated_at' => '2020-10-11 08:06:38',
                'url' => '',
            ),
            1 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-images',
                'id' => 2,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.media.index',
                'target' => '_self',
                'title' => 'Media',
                'updated_at' => '2020-11-16 02:40:20',
                'url' => '',
            ),
            2 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-person',
                'id' => 3,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.users.index',
                'target' => '_self',
                'title' => 'Users',
                'updated_at' => '2020-11-16 02:36:05',
                'url' => '',
            ),
            3 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-lock',
                'id' => 4,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.roles.index',
                'target' => '_self',
                'title' => 'Roles',
                'updated_at' => '2020-11-16 02:36:01',
                'url' => '',
            ),
            4 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-tools',
                'id' => 5,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Tools',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            5 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-list',
                'id' => 6,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.menus.index',
                'target' => '_self',
                'title' => 'Menu Builder',
                'updated_at' => '2020-11-16 02:31:07',
                'url' => '',
            ),
            6 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-data',
                'id' => 7,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.database.index',
                'target' => '_self',
                'title' => 'Database',
                'updated_at' => '2020-11-16 02:31:07',
                'url' => '',
            ),
            7 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-compass',
                'id' => 8,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.compass.index',
                'target' => '_self',
                'title' => 'Compass',
                'updated_at' => '2020-11-16 02:31:07',
                'url' => '',
            ),
            8 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-bread',
                'id' => 9,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.bread.index',
                'target' => '_self',
                'title' => 'BREAD',
                'updated_at' => '2020-11-16 02:31:07',
                'url' => '',
            ),
            9 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:38',
                'icon_class' => 'voyager-settings',
                'id' => 10,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.settings.index',
                'target' => '_self',
                'title' => 'Settings',
                'updated_at' => '2020-11-16 02:36:21',
                'url' => '',
            ),
            10 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:39',
                'icon_class' => 'voyager-categories',
                'id' => 11,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.categories.index',
                'target' => '_self',
                'title' => 'Categories',
                'updated_at' => '2020-11-16 02:40:45',
                'url' => '',
            ),
            11 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:39',
                'icon_class' => 'voyager-news',
                'id' => 12,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.posts.index',
                'target' => '_self',
                'title' => 'Posts',
                'updated_at' => '2020-11-16 02:37:02',
                'url' => '',
            ),
            12 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:06:39',
                'icon_class' => 'voyager-hook',
                'id' => 14,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 5,
                'route' => 'voyager.hooks',
                'target' => '_self',
                'title' => 'Hooks',
                'updated_at' => '2020-11-16 02:31:07',
                'url' => '',
            ),
            13 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-11 08:13:53',
                'icon_class' => 'voyager-buy',
                'id' => 15,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.orders.index',
                'target' => '_self',
                'title' => 'Orders',
                'updated_at' => '2020-11-16 02:40:45',
                'url' => '',
            ),
            14 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-12 06:18:19',
                'icon_class' => 'voyager-shop',
                'id' => 16,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => NULL,
                'route' => 'voyager.shops.index',
                'target' => '_self',
                'title' => 'Shops',
                'updated_at' => '2020-11-16 02:37:16',
                'url' => '',
            ),
            15 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-12 09:02:30',
                'icon_class' => 'voyager-bag',
                'id' => 17,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.products.index',
                'target' => '_self',
                'title' => 'Products',
                'updated_at' => '2020-11-16 02:40:45',
                'url' => '',
            ),
            16 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-14 14:44:03',
                'icon_class' => NULL,
                'id' => 18,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.coupons.index',
                'target' => '_self',
                'title' => 'Coupons',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            17 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-10-15 12:12:53',
                'icon_class' => NULL,
                'id' => 19,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => 'null',
                'parent_id' => 44,
                'route' => 'seller.orders.index',
                'target' => '_blank',
                'title' => 'Order Management',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            18 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-10-15 16:39:04',
                'icon_class' => 'voyager-credit-card',
                'id' => 20,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.transactions.index',
                'target' => '_self',
                'title' => 'Transactions',
                'updated_at' => '2020-11-16 02:44:14',
                'url' => '',
            ),
            19 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-15 16:40:36',
                'icon_class' => NULL,
                'id' => 21,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.sub-orders.index',
                'target' => '_self',
                'title' => 'Sub Orders',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            20 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-31 08:16:38',
                'icon_class' => NULL,
                'id' => 25,
                'menu_id' => 1,
                'order' => 3,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.custom-pages.index',
                'target' => '_self',
                'title' => 'Custom Pages',
                'updated_at' => '2020-11-16 02:37:00',
                'url' => '',
            ),
            21 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-31 11:20:38',
                'icon_class' => NULL,
                'id' => 26,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.home-videos.index',
                'target' => '_self',
                'title' => 'Home Videos',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            22 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-31 12:49:37',
                'icon_class' => NULL,
                'id' => 28,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.contacts.index',
                'target' => '_self',
                'title' => 'Contacts',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            23 => 
            array (
                'color' => NULL,
                'created_at' => '2020-10-31 13:03:21',
                'icon_class' => NULL,
                'id' => 30,
                'menu_id' => 1,
                'order' => 7,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.faqs.index',
                'target' => '_self',
                'title' => 'Faqs',
                'updated_at' => '2020-11-16 02:40:20',
                'url' => '',
            ),
            24 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-10-31 17:08:30',
                'icon_class' => 'voyager-truck',
                'id' => 31,
                'menu_id' => 1,
                'order' => 4,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.wholesales.index',
                'target' => '_self',
                'title' => 'Wholesales',
                'updated_at' => '2020-11-16 02:42:22',
                'url' => '',
            ),
            25 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-01 14:23:14',
                'icon_class' => NULL,
                'id' => 32,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.product-attributes.index',
                'target' => '_self',
                'title' => 'Product Attributes',
                'updated_at' => '2020-11-16 02:40:45',
                'url' => '',
            ),
            26 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-01 14:35:57',
                'icon_class' => NULL,
                'id' => 33,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.videos.index',
                'target' => '_self',
                'title' => 'Videos',
                'updated_at' => '2020-11-16 02:40:20',
                'url' => '',
            ),
            27 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-01 14:36:30',
                'icon_class' => NULL,
                'id' => 34,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.video-categories.index',
                'target' => '_self',
                'title' => 'Video Categories',
                'updated_at' => '2020-11-16 02:40:20',
                'url' => '',
            ),
            28 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-01 15:23:35',
                'icon_class' => NULL,
                'id' => 35,
                'menu_id' => 1,
                'order' => 10,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.ebook-requests.index',
                'target' => '_self',
                'title' => 'Ebook Requests',
                'updated_at' => '2020-11-16 02:40:21',
                'url' => '',
            ),
            29 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-02 06:48:43',
                'icon_class' => 'voyager-wallet',
                'id' => 36,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.wallets.index',
                'target' => '_self',
                'title' => 'Wallets',
                'updated_at' => '2020-11-16 02:43:06',
                'url' => '',
            ),
            30 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-02 06:50:39',
                'icon_class' => NULL,
                'id' => 37,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.reward-points.index',
                'target' => '_self',
                'title' => 'Reward Points',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            31 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-02 06:52:49',
                'icon_class' => 'voyager-tag',
                'id' => 38,
                'menu_id' => 1,
                'order' => 9,
                'parameters' => 'null',
                'parent_id' => NULL,
                'route' => 'voyager.gift-card-purchases.index',
                'target' => '_self',
                'title' => 'Gift Card Purchases',
                'updated_at' => '2020-11-16 02:43:59',
                'url' => '',
            ),
            32 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-02 06:57:46',
                'icon_class' => NULL,
                'id' => 39,
                'menu_id' => 1,
                'order' => 8,
                'parameters' => NULL,
                'parent_id' => 44,
                'route' => 'voyager.gift-cards.index',
                'target' => '_self',
                'title' => 'Gift Cards',
                'updated_at' => '2020-11-16 02:40:46',
                'url' => '',
            ),
            33 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-02 06:58:31',
                'icon_class' => NULL,
                'id' => 40,
                'menu_id' => 1,
                'order' => 11,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.site-reviews.index',
                'target' => '_self',
                'title' => 'Site Reviews',
                'updated_at' => '2020-11-16 02:40:27',
                'url' => '',
            ),
            34 => 
            array (
                'color' => NULL,
                'created_at' => '2020-11-12 06:05:07',
                'icon_class' => NULL,
                'id' => 41,
                'menu_id' => 1,
                'order' => 5,
                'parameters' => NULL,
                'parent_id' => 46,
                'route' => 'voyager.post-categories.index',
                'target' => '_self',
                'title' => 'Post Categories',
                'updated_at' => '2020-11-16 02:40:20',
                'url' => '',
            ),
            35 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-15 18:59:22',
                'icon_class' => 'voyager-settings',
                'id' => 42,
                'menu_id' => 1,
                'order' => 1,
                'parameters' => 'null',
                'parent_id' => 5,
                'route' => 'index',
                'target' => '_blank',
                'title' => 'Shop Status',
                'updated_at' => '2020-11-15 23:16:23',
                'url' => '',
            ),
            36 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-16 01:57:16',
                'icon_class' => 'voyager-logbook',
                'id' => 43,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => 'null',
                'parent_id' => 5,
                'route' => 'voyager.expenses.index',
                'target' => '_self',
                'title' => 'Expenses',
                'updated_at' => '2020-11-16 02:45:09',
                'url' => '',
            ),
            37 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-16 02:33:03',
                'icon_class' => 'voyager-treasure',
                'id' => 44,
                'menu_id' => 1,
                'order' => 2,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Shop Management',
                'updated_at' => '2020-11-16 02:41:53',
                'url' => '',
            ),
            38 => 
            array (
                'color' => '#000000',
                'created_at' => '2020-11-16 02:35:34',
                'icon_class' => 'voyager-browser',
                'id' => 46,
                'menu_id' => 1,
                'order' => 6,
                'parameters' => '',
                'parent_id' => NULL,
                'route' => NULL,
                'target' => '_self',
                'title' => 'Site Management',
                'updated_at' => '2020-11-16 02:43:30',
                'url' => '',
            ),
        ));
        
        
    }
}