<?php

use Illuminate\Database\Seeder;

class OrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('orders')->delete();
        
        \DB::table('orders')->insert(array (
            0 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-10-01 22:47:41',
                'grand_total' => 45000.0,
                'id' => 1,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb1236d7c6f6',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:47:41',
                'user_id' => 3,
            ),
            1 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:49:27',
                'grand_total' => 45000.0,
                'id' => 2,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb123d70d971',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:49:27',
                'user_id' => 3,
            ),
            2 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:50:26',
                'grand_total' => 45000.0,
                'id' => 3,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12411eed76',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:50:26',
                'user_id' => 3,
            ),
            3 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:51:00',
                'grand_total' => 45000.0,
                'id' => 4,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12434472b4',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:51:00',
                'user_id' => 3,
            ),
            4 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:52:14',
                'grand_total' => 45000.0,
                'id' => 5,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb1247ed396e',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:52:14',
                'user_id' => 3,
            ),
            5 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:53:12',
                'grand_total' => 45000.0,
                'id' => 6,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb124b83c6e6',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:53:12',
                'user_id' => 3,
            ),
            6 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:53:32',
                'grand_total' => 45000.0,
                'id' => 7,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb124cc1e5a1',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:53:32',
                'user_id' => 3,
            ),
            7 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:55:04',
                'grand_total' => 45000.0,
                'id' => 8,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12528ac783',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:55:04',
                'user_id' => 3,
            ),
            8 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:55:50',
                'grand_total' => 45000.0,
                'id' => 9,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12556f088f',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:55:50',
                'user_id' => 3,
            ),
            9 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-15 23:59:12',
                'grand_total' => 45000.0,
                'id' => 10,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb1262017919',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-15 23:59:12',
                'user_id' => 3,
            ),
            10 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-16 00:33:43',
                'grand_total' => 200.0,
                'id' => 11,
                'is_paid' => 0,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12e37caa2e',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-16 00:33:43',
                'user_id' => 3,
            ),
            11 => 
            array (
                'billing_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'billing_city' => 'Dhaka',
                'billing_fullname' => 'Jamilur rahman',
                'billing_phone' => '01787201430',
                'billing_state' => 'Dhaka',
                'billing_zipcode' => '1213',
                'created_at' => '2020-11-16 00:37:00',
                'grand_total' => 45000.0,
                'id' => 12,
                'is_paid' => 1,
                'item_count' => 1,
                'notes' => NULL,
                'order_number' => 'OrderNumber-5fb12f143bcb7',
                'payment_method' => 'cash_on_delivery',
                'shipping_address' => 'Cha-214, TB Gate, Mohakhali, Dhaka',
                'shipping_city' => 'Dhaka',
                'shipping_fullname' => 'Jamilur rahman',
                'shipping_phone' => '01787201430',
                'shipping_state' => 'Dhaka',
                'shipping_zipcode' => '1213',
                'status' => 'pending',
                'updated_at' => '2020-11-16 02:46:16',
                'user_id' => 3,
            ),
        ));
        
        
    }
}