version: '3.2'


services:
  db:
    image: mysql:8.0
    container_name: DB
    restart: always
    ports:
      - '6603:3306'
    environment:
      MYSQL_ROOT_PASSWORD: keepaway
    volumes:
      - my-datavolume:/var/lib/mysql

  app:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db



volumes:
  my-datavolume: